[package]
name = "ExpireFolder"
version = "0.1.0"
authors = ["Gioele F. <gioele.fiorenza2000@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.29", features = ["derive"] }
